export default {
  smartBicho: {
    137: '0xasdasda231CONTRATO',
  },
}

export const Modos = [
  {
    modo: 'Seco',
  },
  {
    modo: 'Cercado',
  },
  {
    modo: 'Duque',
  },
  {
    modo: 'Terno',
  },
  {
    modo: 'Vai e Vem',
  },
]

export const Tipos = [
  {
    animal: 'Avestruz',
    numero1: '01',
    numero2: '02',
    numero3: '03',
    numero4: '04',
    numeroIndice: '1',
    urlImage: 'https://ibb.co/g9Vc1St'

  },
  {
    animal: 'Águia',
    numero1: '05',
    numero2: '06',
    numero3: '07',
    numero4: '08',
    numeroIndice: '2',
  },
  {
    animal: 'Burro',
    numero1: '09',
    numero2: '10',
    numero3: '11',
    numero4: '12',
    numeroIndice: '3',
  },
  {
    animal: 'Borboleta',
    numero1: '13',
    numero2: '14',
    numero3: '15',
    numero4: '16',
    numeroIndice: '4',
  },
  {
    animal: 'Cachorro',
    numero1: '17',
    numero2: '18',
    numero3: '19',
    numero4: '20',
    numeroIndice: '5',
  },
  {
    animal: 'Cabra',
    numero1: '21',
    numero2: '22',
    numero3: '23',
    numero4: '24',
    numeroIndice: '6',
  },
  {
    animal: 'Carneiro',
    numero1: '25',
    numero2: '26',
    numero3: '27',
    numero4: '28',
    numeroIndice: '7',
  },
  {
    animal: 'Camelo',
    numero1: '29',
    numero2: '30',
    numero3: '31',
    numero4: '32',
    numeroIndice: '8',
  },
  {
    animal: 'Cobra',
    numero1: '33',
    numero2: '34',
    numero3: '35',
    numero4: '36',
    numeroIndice: '9',
  },
  {
    animal: 'Coelho',
    numero1: '37',
    numero2: '38',
    numero3: '39',
    numero4: '40',
    numeroIndice: '10',
  },
  {
    animal: 'Cavalo',
    numero1: '41',
    numero2: '42',
    numero3: '43',
    numero4: '44',
    numeroIndice: '11',
  },
  {
    animal: 'Elefante',
    numero1: '45',
    numero2: '46',
    numero3: '47',
    numero4: '48',
    numeroIndice: '12',
  },
  {
    animal: 'Galo',
    numero1: '49',
    numero2: '50',
    numero3: '51',
    numero4: '52',
    numeroIndice: '13',
  },
  {
    animal: 'Gato',
    numero1: '53',
    numero2: '54',
    numero3: '55',
    numero4: '56',
    numeroIndice: '14',
  },
  {
    animal: 'Jacaré',
    numero1: '57',
    numero2: '58',
    numero3: '59',
    numero4: '60',
    numeroIndice: '15',
  },
  {
    animal: 'Leão',
    numero1: '61',
    numero2: '62',
    numero3: '63',
    numero4: '64',
    numeroIndice: '16',
  },
  {
    animal: 'Macaco',
    numero1: '65',
    numero2: '66',
    numero3: '67',
    numero4: '68',
    numeroIndice: '17',
  },
  {
    animal: 'Porco',
    numero1: '69',
    numero2: '70',
    numero3: '71',
    numero4: '72',
    numeroIndice: '18',
  },
  {
    animal: 'Pavão',
    numero1: '73',
    numero2: '74',
    numero3: '75',
    numero4: '76',
    numeroIndice: '19',
  },
  {
    animal: 'Peru',
    numero1: '77',
    numero2: '78',
    numero3: '79',
    numero4: '80',
    numeroIndice: '20',
  },
  {
    animal: 'Touro',
    numero1: '81',
    numero2: '82',
    numero3: '83',
    numero4: '84',
    numeroIndice: '21',
  },
  {
    animal: 'Tigre',
    numero1: '85',
    numero2: '86',
    numero3: '87',
    numero4: '88',
    numeroIndice: '22',
  },
  {
    animal: 'Urso',
    numero1: '89',
    numero2: '90',
    numero3: '91',
    numero4: '92',
    numeroIndice: '23',
  },
  {
    animal: 'Veado',
    numero1: '93',
    numero2: '94',
    numero3: '95',
    numero4: '96',
    numeroIndice: '24',
  },
  {
    animal: 'Vaca',
    numero1: '97',
    numero2: '98',
    numero3: '99',
    numero4: '00',
    numeroIndice: '25',
  },
]
