import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import App from '../components/App';

export default function Home() {
  return (
    <div className={styles.container} data-theme="fantasy">
      <Head>
        <title>Revolução dos Bichos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <Header />

      <App />
    </div>
  );
}
