import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Header from '../components/Header';
import App from '../components/App';
import { TestRead, Write } from '../components/types';
import { Account } from '../components/Account';
import Send from '../components/types/milha';
import Appnew from '../components/types/dezena copy';

export default function Home() {
  return (
    <div className={styles.container} data-theme="fantasy">
      <Head>
        <title>Revolução dos Bichos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Account/>
      <TestRead/>
      <Write/>
      <Send/>
      <App />
<<<<<<< HEAD

      <Footer />
      <Appnew/>
=======
>>>>>>> cdcdfe562af24d7b3480a8ba0836dcc9f7c13a35
    </div>
  );
}
